Core:
    #The amount of XP deposited and withdrawn at a time. Setting this to values under 10 may cause lag on large servers.
    storageAmount: 25
    #The maximum amount of XP a player can store in any one sign. 4625 is level 50. Use /anima levelxp <level> to get other values.
    maxXP: 4625
    #Check for new versions on startup
    versionCheck: true

Economy:
    #The cost to create an Anima sign. 0 to disable, decimals allowed.
    signCost: 0
    #The cost to deposit or withdraw 1 XP. Note that this is multiplied by storageAmount, above, when making deposits and withdrawals.
    #0 to disable, decimals allowed.
    depositCost: 0
    withdrawCost: 0

configVer: 1