Core:
    #The amount of XP deposited and withdrawn at a time. Setting this to values under 10 may cause lag on large servers.
    storageAmount: 25
    #The maximum amount of XP a player can store in any one sign. 4625 is level 50. Use /anima levelxp <level> to get other values.
    maxXP: 4625
    #Check for new versions on startup
    versionCheck: true

Economy:
    #The cost to create an Anima sign. 0 to disable, decimals allowed.
    signCashCost: 0
    #The cost to deposit or withdraw 1 XP. Note that this is multiplied by storageAmount, above, when making deposits and withdrawals.
    #0 to disable, decimals allowed.
    depositCashCost: 0
    withdrawCashCost: 0

XPCosts:
    #The cost in XP to create an Anima sign. 0 to disable, integers only.
    signXPCost: 0
    #The cost to deposit or withdraw XP as a percentage of the deposited or withdrawn amount.
    #For example, entering 1 for depositXPCost will result in the player paying 1 XP for depositing 100 XP or less.
    #IMPORTANT: Deposit costs are always rounded up, so the minimum cost is 1 XP! 
    #0 to disable, decimals allowed.
    depositXPCost: 0
    withdrawXPCost: 0

configVer: 2